### ISSUE TITLE
Octave on Windows get stuck on Busy...

### ISSUE THREAD

**Issue by Foadsf** [texmacs/plugins#11]
As I have explained [here ](https://stackoverflow.com/q/56570776/4999991)both Octave and Scilab sessions get stuck on `Busy...`:

<pre>
<center>
<img src="https://i.stack.imgur.com/nCFiJ.png" width="600">
</center>
</pre>

**Comment by pireddag** [comment]
Hi Foad: I don't have an answer for this problem, but if you post your question in the TeXmacs mailing list (information on how to subscribe is here: http://www.texmacs.org/tmweb/home/ml.en.html) there is a chance someone will answer (I have subscribed the list since a few months and it is active). 

As a separate thing, if you post this question on the StackExchange TeXmacs proposal it will be helpful for the TeXmacs project - there it will not be possible to answer it, but it will help the proposal to advance,  someone will be able to upvote it (upvoting questions in this moment is important because the upvoting requirement has not yet been satisfied).

Giovanni

**Comment by sadhen** [comment]
Well, welcome to report bugs here, @Foadsf 

My Octave 4.4.1 works fine on Debian. You may install Octave 4.x.

According to https://github.com/texmacs/plugins , the octave subdir was updated 2 years ago. The plugin may not support the latest octave.

**Comment by Foadsf** [comment]
@sadhen Thank you. 

But Octave 4.4.1 is pretty outdated. As I have explained [here](https://stackoverflow.com/q/56570776/4999991) I'm using 5.1.0 on Windows 10. any idea what is the main cause of the problem?

**Comment by sadhen** [comment]
Well, I do not have a Windows machine these days. I will look into this issue later when I have my old Windows laptap at hands.

**Comment by mgubi** [comment]
Please try to modify the file in `plugins/octave/octave/tm-strart.m` to looks  like
```
d=getenv("TEXMACS_PATH");
if (length(d) > 0)
    addpath("tm:polynomial:plot")
    tmrepl
endif
```
adding the line `addpath("tm:polynomial:plot")` so that Octave know where to find the functions.

**Comment by Foadsf** [comment]
@mgubi I tried this but it did not solve the problem. running the `C:\Program Files (x86)\TeXmacs\plugins\octave\bin>tm_octave.bat` returns:

~~~
verbatim:GNU Octave, version 5.1.0
Copyright (C) 2019 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.

Octave was configured for "x86_64-w64-mingw32".

Additional information about Octave is available at https://www.octave.org.

Please contribute if you find this software useful.
For more information, visit https://www.octave.org/get-involved.html

Read https://www.octave.org/bugs.html to learn how to submit bug reports.
~~~

with no errors!

**Comment by mgubi** [comment]
Can you try to do the same inside the shell  session of texmacs, namely calling directly tm_octave.bat file?

**Comment by Foadsf** [comment]
@mgubi shell session on Windows? 🤔

<pre>
                <img src="https://user-images.githubusercontent.com/12762442/60372299-81ccc600-99fc-11e9-8983-fcafe24968f4.png" width="300">
</pre>

**Comment by Foadsf** [comment]
the same issue happens for Scilab:


<pre>
<img src="https://user-images.githubusercontent.com/12762442/60372353-a88afc80-99fc-11e9-8d07-24545a877044.PNG" width="700">
</pre>

**Comment by imwhl** [comment]
@Foadsf  You have to modify the original octave.bat. In the Windows system, the command: "octave -v" in this file won't return. Hence, delete this line could solve your problem.
the orginal octave.bat:
@echo off
rem denis RAUX LIX 2013
rem a simple trick to
set /p DUMMY="verbatim:" <nul
octave -v
rem cd $TEXMACS_PATH/plugins/octave/octave; exec octave -qi tm-start.oct
cd %TEXMACS_PATH%\plugins\octave\octave
octave -qi tm-start.oct

Change it to:
@echo off
rem denis RAUX LIX 2013
rem a simple trick to
set /p DUMMY="verbatim:" <nul
rem cd $TEXMACS_PATH/plugins/octave/octave; exec octave -qi tm-start.oct
rem octave -v
cd %TEXMACS_PATH%\plugins\octave\octave
octave -qi tm-start.m

Good luck!

**Comment by sadhen** [comment]
@imwhl  I have applied your changes. The Octave plugin on Windows should work fine the next release.

**Comment by sadhen** [comment]
@Foadsf Shell session is not supported on Windows

**Comment by sadhen** [comment]
There is another known issue for the octave plugin:

https://savannah.gnu.org/bugs/?57495

The plugin works fine, it is a packaging problem.
