### ISSUE TITLE
flush_newline (2) error

### ISSUE THREAD

**Issue by pdiazs** [texmacs/plugins#16]
When i launch sympy plugin i find this error 
flush_newline  function not defined

I just comment line 60 in tm_sympy.py and it apparently works (at least reaches python)

but when I launch a sympy expression, i get
"flush_latex (latex (data))
NameError: global name 'flush_latex' is not defined"

Regards

Pedro

**Comment by sadhen** [comment]
@pdiazs  

What TeXmacs version you are using? It seems you are under develop mode. Do you know what is develop mode? Have you changed the source code of the plugin?
