### ISSUE TITLE
error handling of absent xypic package

### ISSUE THREAD

**Issue by woutersj** [texmacs/plugins#18]
If I execute the xypic examples in graph-demo.en.tm on a machine that doesn't have xypic installed, the session just hangs on a "Busy..." message. If I try to press "Interrupt execution" TeXmacs crashes, often taking the entire Wayland session down with it, too. On Xorg only TeXmacs crashes.
The plugin works once I install xypic.

**Comment by sadhen** [comment]
Here is how I checked the installation of xypic:
```
(define (xypic-exists?)
  (and (url-exists-in-path? "latex")
       (cond ((url-exists-in-path? "kpsewhich")
              (!= (eval-system "kpsewhich xy.sty") ""))
             (else #f))))
```

**Comment by sadhen** [comment]
For non-exist session, we should kindly report the status of the session instead of only showing a Buzy message.

**Comment by woutersj** [comment]
Thanks for the quick reply. If I execute '(xypic-exists?)' in a Scheme session, it correctly tells me whether or not xypic is installed.

I also get the same issue when running tikz code with missing libraries, e.g. when running [this example](https://texmacs.github.io/notes/docs/a-tikz-example.html) without tikz-3dplot installed.

**Comment by sadhen** [comment]
> I also get the same issue when running tikz code with missing libraries, e.g. when running this example without tikz-3dplot installed.

These are known flaws, but these are out of the TeXmacs scope.

**Comment by sadhen** [comment]
I'm working on closing the issues functionality of http://github.com/texmacs
