### ISSUE TITLE
Error message with sage plugin

### ISSUE THREAD

**Issue by woutersj** [texmacs/plugins#19]
I get the following error message when starting a Sage session:
```
SageMath version 9.2, Release Date: 2020-10-24
bash: cannot set terminal process group (2402): Inappropriate ioctl for device
bash: no job control in this shell
```

/usr/bin/sage on my system (Fedora 33) start with `#!/usr/bin/bash -i`. Changing that to `#!/usr/bin/bash --login` makes the message go away.

**Comment by sadhen** [comment]
It seems to be a problem in the `sage` shell script.

**Comment by sadhen** [comment]
```
$ head -n 1 /usr/bin/sage
#!/usr/bin/env bash
```
Here is the first line of `/usr/bin/sage` in debian sid (sage 9.2).

**Comment by sadhen** [comment]
I suggest that you should submit a bug report to the RPM package of SageMath. For debian, it works fine.
