### ISSUE TITLE
multiline input to sage fold

### ISSUE THREAD

**Issue by woutersj** [texmacs/plugins#20]
I can't seem to get multiline input to work in a Sage Math fold. It does work for other plugins (including Python).
E.g. the input
```
x = 3
print(x)
```
results in
```
File "<string>", line 1
    x = 3print(x)
      ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

  File "tm_sage", line 1
    x = 3print(x)
         ^
SyntaxError: invalid syntax
```
Pasting the exact same input into a Python fold does work.

**Comment by woutersj** [comment]
Newlines characters aren't being passed to the sage plugin. I've managed to make multiline input work in sage sessions by adding a serializer function to `init-sage.scm` (as is done in `init-python.scm`) and adapting `tm_sage.py` to parse the serialized input (as is done in `tm_python.py`).

For reasons still unclear to me this does not fix the multiline issue in folds.

Additionaly the R and Octave plugins also have issues with multiline input.

**Comment by sadhen** [comment]
The R plugin should be simplified into pure R by removing `tm_r.c`. And the octave plugin has been rewrited. I will try to fix the multiline input issue for octave later.

**Comment by woutersj** [comment]
I've added a serializer function to the octave plugin to make multiline input work, see [this commit](https://github.com/woutersj/octave/commit/4ae99dc37d93f9f6d17eaecce6e2fafcb91431eb).

Some further changes are still needed, as the check for whether or not to display the answer in `tmrepl.m` only checks if the last character is a colon, which isn't correct for multi-line input.

It seems to me that the standard octave repl does some parsing to see whether multiline input is required (e.g. when the keyword "function" is input without a closing "endfunction").

**Comment by woutersj** [comment]
I've created a PR for octave in the octave repository. I'm suppressing output from intermediate commands without a semincolon. Only the final command creates output. This is in line with the behaviour of the Sage and Python plugins.
