### ISSUE TITLE
Octave plugin error of undefined tmrepl in tm-start.m

### ISSUE THREAD

**Issue by chen-chao** [texmacs/plugins#7]
I've met an error of "tmrepl undefined in tm-start.m" when using octave session in TeXmacs. It was solved by adding "$TEXMACS_PATH/plugins/octave/octave/tm" to octave's load path. Then octave works well in TeXmacs so far.

Some related information:

OS: Arch Linux
TeXmacs version: 1.99.8
Octave version: 5.1.0

Hope it helps.

**Comment by chen-chao** [comment]
OK, I've found the .octaverc file in the project which fixes the issue, but not contained in my installed TeXmacs. Maybe this is a packaging problem.

**Comment by sadhen** [comment]
Next time, for Octave related bugs, please report to https://github.com/texmacs/octave.
